apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2025-05-01T16:23:55Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-project
  name: hello-project
  namespace: default
  resourceVersion: "33347"
  uid: e0224d05-6787-455b-b03f-edb0fcb646de
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.239.113
  clusterIPs:
  - 34.118.239.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30689
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-project
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.196.158.223
      ipMode: VIP
